<?php

/**
 * Spec 068 US9 (FR-160) — Docs UI navigation contract.
 *
 * The docs site is Astro + Starlight, which ships the sidebar, full-text search (the
 * Cmd+K command palette), code-copy actions, previous/next pagination, and the on-page
 * table of contents. This test verifies the CoreX configuration keeps those on and adds
 * the one feature Starlight does not ship by default — a working version selector — plus
 * the autogenerated API/class reference. It runs in the PHP suite because docs-app has
 * no separate JS test runner and the root Jest run excludes docs-app.
 *
 * @package Corex\Tests\Unit\Docs
 */

declare(strict_types=1);

use Corex\Tests\Support\ThemeContract;

function docsFile(string $relative): string
{
    return (string) file_get_contents(ThemeContract::root() . '/docs-app/' . $relative);
}

it('keeps the sidebar and the autogenerated API/class reference', function () {
    $config = docsFile('astro.config.mjs');

    expect($config)->toContain('sidebar:')
        ->and($config)->toContain("autogenerate: { directory: 'reference' }");

    expect(is_file(ThemeContract::root() . '/docs-app/src/content/docs/reference/index.md'))->toBeTrue();
});

it('registers the version-selector component override', function () {
    $config = docsFile('astro.config.mjs');

    expect($config)->toContain('components:')
        ->and($config)->toContain('SiteTitle:')
        ->and($config)->toContain('./src/components/SiteTitleWithVersion.astro');

    expect(is_file(ThemeContract::root() . '/docs-app/src/components/SiteTitleWithVersion.astro'))->toBeTrue();
    expect(docsFile('src/components/SiteTitleWithVersion.astro'))
        ->toContain('@astrojs/starlight/components/SiteTitle.astro'); // wraps the default
});

it('ships a functional version selector wired to real release history', function () {
    $select = docsFile('src/components/VersionSelect.astro');

    expect($select)->toContain('data-corex-version')
        ->and($select)->toContain('CURRENT_VERSION')
        ->and($select)->toContain('RELEASES_URL')
        ->and($select)->toContain("window.location.href = href"); // real navigation
});

it('keeps the documented version in sync with the framework version', function () {
    $version = docsFile('src/version.ts');
    $core = (string) file_get_contents(ThemeContract::root() . '/plugins/corex-core/corex-core.php');

    preg_match("/COREX_CORE_VERSION', '([^']+)'/", $core, $coreMatch);
    preg_match("/CURRENT_VERSION = '([^']+)'/", $version, $docsMatch);

    expect($docsMatch[1] ?? 'x')->toBe($coreMatch[1] ?? 'y');
});
