/**
 * Corex — ESLint flat config.
 *
 * This file exists for one reason: scope. `wp-scripts lint-js` with no project config lints `.`
 * under the default config, whose global ignores are only `**\/build/**`, `**\/node_modules/**`
 * and `**\/vendor/**`. This repository also contains a full WordPress install at `wp/` and the
 * generated shared-host bundle at `dist/`, so the default run walked tens of thousands of files
 * that are not ours and never terminated in practice — which is why `lint:js` was never gated in
 * CI while `lint:css` (which has `.stylelintignore`) always could be. The ignore list below is the
 * `.stylelintignore` list plus `docs-app/`, so both linters see very nearly the same tree.
 *
 * Providing any `eslint.config.*` makes wp-scripts stop passing its own `--config`, so the
 * WordPress defaults have to be re-exported here rather than inherited implicitly.
 */

const wpScriptsConfig = require( '@wordpress/scripts/config/eslint.config.cjs' );

module.exports = [
	{
		ignores: [
			'**/node_modules/**',
			'**/vendor/**',
			'**/build/**',
			'**/dist/**',
			'wp/**',
			// Generated by the browser suite, not authored here.
			'playwright-report/**',
			'test-results/**',
			'coverage/**',
			/*
			 * The docs site is a separate npm project, not a workspace of this one: it has its
			 * own `package.json` and its own `node_modules`, and the root `npm ci` deliberately
			 * does not install them. Linting it from here therefore resolves imports against a
			 * dependency tree that is present on a developer's machine and absent in CI — which
			 * is exactly how it failed: `astro/config` and `@astrojs/starlight` are unresolvable
			 * from the root install. It is linted by its own toolchain, from its own directory.
			 */
			'docs-app/**',
		],
	},
	...wpScriptsConfig,

	/*
	 * `@wordpress/*` imports are build-time externals, not npm dependencies.
	 *
	 * `@wordpress/dependency-extraction-webpack-plugin` (part of the wp-scripts webpack config)
	 * rewrites every one of them to the `window.wp.*` global WordPress already serves, and emits
	 * the matching script handles into `*.asset.php` — for example
	 * `plugins/corex-blocks/build/blocks/entity-field/index.asset.php`, whose dependency list is
	 * `wp-block-editor`, `wp-blocks`, `wp-components`, `wp-i18n`, `wp-server-side-render`. They are
	 * never bundled and never installed, which is why the workspace packages declare no runtime
	 * dependencies at all. Resolving them from `node_modules` is therefore the wrong question:
	 * installing them would be the actual mistake, because a bundled copy would shadow the version
	 * the host WordPress runs.
	 */
	{
		files: [ '**/*.js', '**/*.jsx' ],
		rules: {
			'import/no-unresolved': [ 'error', { ignore: [ '^@wordpress/' ] } ],
			'import/no-extraneous-dependencies': [
				'error',
				{ peerDependencies: true, bundledDependencies: false },
			],
		},
		settings: {
			'import/core-modules': [
				'@wordpress/api-fetch',
				'@wordpress/block-editor',
				'@wordpress/blocks',
				'@wordpress/components',
				'@wordpress/compose',
				'@wordpress/data',
				'@wordpress/element',
				'@wordpress/i18n',
				'@wordpress/server-side-render',
				'@wordpress/url',
			],
		},
	},

	/*
	 * The repository's own Node tooling. These are command-line scripts whose entire job is to
	 * report to a terminal — `no-console` would be telling them not to have output.
	 */
	{
		files: [ 'scripts/**/*.mjs', 'scripts/**/*.js' ],
		rules: {
			'no-console': 'off',
		},
	},
];
