/**
 * The repository states one version, tracks no generated clutter, and keeps its root readable.
 *
 * Everything here is asserted against **what git actually tracks**, not against the working tree.
 * The distinction is the point: a `.gitignore` rule tells you what git was *asked* to skip, and this
 * asks what it *kept*. Spec 097 lost a fixture to a glob that was doing its job — a `fix` wildcard
 * under `tests/e2e`, there for throwaway render output, which also swallowed `tests/e2e/fixtures`.
 * The only symptom until CI ran was a commit that looked complete.
 *
 * The three checks are the three ways this repository has actually drifted:
 *
 *   1. Generated or exported files reaching the index, where they rot and bloat clones.
 *   2. Root Markdown accumulating until the canonical set is no longer findable in it.
 *   3. A version declared in prose disagreeing with `package.json`, or a document announcing a
 *      release that has no tag — which is exactly the state this repository was in before v0.41.0
 *      (`PROGRESS.md` opened with "v0.41.0 released" while the newest tag was v0.40.0).
 *
 * Deliberately permissive about specs, evidence, translations and documentation: those are the
 * record this project is built on, and a hygiene guard that fought them would be turned off.
 */
const { execFileSync } = require( 'node:child_process' );
const fs = require( 'node:fs' );
const path = require( 'node:path' );

const repositoryRoot = path.resolve( __dirname, '..' );

/** Every path git tracks, one per line. */
const trackedFiles = execFileSync(
	'git',
	[ '-C', repositoryRoot, 'ls-files' ],
	{
		encoding: 'utf8',
		maxBuffer: 32 * 1024 * 1024,
	}
)
	.split( /\r?\n/ )
	.filter( Boolean );

/**
 * What must never be tracked, and the reason, so a failure explains itself.
 *
 * Each entry is matched against the full repository-relative path.
 */
const FORBIDDEN = [
	[ /^dist\/|\/dist\//, 'build output — generated by npm run build:dist' ],
	[ /^build\/|\/build\//, 'build output — generated by npm run build' ],
	[
		/^wp\//,
		'a local WordPress install — the monorepo is the source, wp/ is runtime',
	],
	[
		/^vendor\/|\/vendor\//,
		'Composer dependencies — install from composer.lock',
	],
	[
		/^node_modules\/|\/node_modules\//,
		'npm dependencies — install from package-lock.json',
	],
	[ /^output\//, 'ad-hoc local script output' ],
	[ /^test-results\/|\/test-results\//, 'Playwright run output' ],
	[
		/^playwright-report\/|\/playwright-report\//,
		'Playwright report output',
	],
	[
		/^sites\//,
		'a client site implementation — those live in their own repository',
	],
	[
		/\.zip$|\.tar\.gz$|\.tgz$|\.rar$|\.7z$/,
		'an archive — ship releases, not committed archives',
	],
	[ /\.dc\.html$/, 'a raw design-tool export' ],
	[ /(^|\/)support\.js$/, 'a design-export helper script' ],
	[ /\.(bak|orig|swp|tmp)$|~$/, 'an editor or backup artifact' ],
	[ /(^|\/)(\.DS_Store|Thumbs\.db|desktop\.ini)$/, 'an OS artifact' ],
	[
		/(^|\/)\.env(\.|$)/,
		'an environment file — only .env.example belongs in git',
	],
	[
		/(^|\/)(id_rsa|id_ed25519)$|\.pem$|\.p12$|\.pfx$/,
		'a private key or certificate',
	],
];

/** `.env.example` is the deliberate exception to the `.env` rule. */
const FORBIDDEN_EXCEPTIONS = [ /(^|\/)\.env\.example$/ ];

/**
 * The Markdown files allowed to sit at the repository root.
 *
 * A closed list, not a pattern. The root is the first thing a reader sees, and the failure mode this
 * prevents is not one bad file — it is twenty plausible ones, each of which looked reasonable on the
 * day it was added. A new root document is a deliberate decision, so it should cost one line here.
 */
const ALLOWED_ROOT_MARKDOWN = [
	'AGENTS.md',
	'CHANGELOG.md',
	'CLAUDE.md',
	'CODE_OF_CONDUCT.md',
	'CONTRIBUTING.md',
	'DECISIONS.md',
	'PROGRESS.md',
	'PROJECT-STATUS.md',
	'README.md',
	'ROADMAP.md',
	'SECURITY.md',
];

describe( 'tracked files', () => {
	it( 'holds no generated directory, archive, export or secret', () => {
		const offenders = trackedFiles
			.filter(
				( file ) =>
					! FORBIDDEN_EXCEPTIONS.some( ( allowed ) =>
						allowed.test( file )
					)
			)
			.flatMap( ( file ) => {
				const match = FORBIDDEN.find( ( [ pattern ] ) =>
					pattern.test( file )
				);
				return match ? [ `${ file } — ${ match[ 1 ] }` ] : [];
			} );

		expect( offenders ).toEqual( [] );
	} );

	it( 'keeps the repository root to its canonical documents', () => {
		const rootMarkdown = trackedFiles
			.filter( ( file ) => /^[^/]+\.mdx?$/.test( file ) )
			.sort();

		expect( rootMarkdown ).toEqual( ALLOWED_ROOT_MARKDOWN );
	} );

	it( 'keeps every canonical document present', () => {
		// The inverse of the check above, and not redundant with it: an equality assertion fails
		// identically whether a file was added or deleted, and "README.md is missing" deserves to be
		// said in those words rather than inferred from a diff of two lists.
		const missing = ALLOWED_ROOT_MARKDOWN.filter(
			( file ) => ! fs.existsSync( path.join( repositoryRoot, file ) )
		).map( ( file ) => `${ file } is missing from the repository root` );

		expect( missing ).toEqual( [] );
	} );
} );

describe( 'the version the repository claims', () => {
	const declaredVersion = JSON.parse(
		fs.readFileSync( path.join( repositoryRoot, 'package.json' ), 'utf8' )
	).version;

	/**
	 * Where prose states the *current* version, and the pattern that captures it.
	 *
	 * These mirror `Corex\Cli\Release\VersionPlan::PROSE_PATTERNS`, which is what `wp corex version`
	 * stamps. Two lists that must agree is a smell, and it is the lesser one: the stamper is PHP and
	 * runs at release time, this is JavaScript and runs on every pull request. What this catches is a
	 * document edited by hand between releases, which is precisely how these drifted before the
	 * stamper existed.
	 */
	const CURRENT_VERSION_CLAIMS = [
		[ 'README.md', /^## Status: v(\d+\.\d+\.\d+),/m ],
		[ 'README.md', /^wp corex readiness (\d+\.\d+\.\d+)$/m ],
		[ 'ROADMAP.md', /^\*\*Currently released: v(\d+\.\d+\.\d+)\.\*\*/m ],
		[ 'PROJECT-STATUS.md', /^\*\*Version (\d+\.\d+\.\d+)\*\* ·/m ],
	];

	it.each( CURRENT_VERSION_CLAIMS )(
		'%s agrees with package.json',
		( file, pattern ) => {
			const contents = fs.readFileSync(
				path.join( repositoryRoot, file ),
				'utf8'
			);
			const found = contents.match( pattern );

			// A missing anchor is a failure, not a pass. If the sentence is reworded, `wp corex
			// version` stops stamping it silently and the file drifts from the next release onward —
			// so the absence is reported as its own sentence rather than as `null !== '0.41.0'`.
			expect(
				found === null
					? `${ file } no longer carries the sentence the release stamper anchors to: ${ pattern }`
					: found[ 1 ]
			).toBe( declaredVersion );
		}
	);

	it( 'never announces a release that has no tag', () => {
		const tags = new Set(
			execFileSync( 'git', [ '-C', repositoryRoot, 'tag', '--list' ], {
				encoding: 'utf8',
				maxBuffer: 8 * 1024 * 1024,
			} )
				.split( /\r?\n/ )
				.filter( Boolean )
		);

		// Only the present tense. "released as v0.38.1" in a changelog is a true statement about the
		// past; "v0.41.0 released" at the top of a status file, with no v0.41.0 tag anywhere, is the
		// claim this repository actually made and the one worth failing on.
		const announcement = /\bv?(\d+\.\d+\.\d+)\s+(?:is\s+)?released\b/gi;
		const offenders = [];

		for ( const file of [
			'README.md',
			'PROGRESS.md',
			'PROJECT-STATUS.md',
		] ) {
			const contents = fs.readFileSync(
				path.join( repositoryRoot, file ),
				'utf8'
			);

			for ( const match of contents.matchAll( announcement ) ) {
				if ( ! tags.has( `v${ match[ 1 ] }` ) ) {
					offenders.push(
						`${ file }: claims ${ match[ 0 ] }, but no tag v${ match[ 1 ] } exists`
					);
				}
			}
		}

		expect( offenders ).toEqual( [] );
	} );
} );

describe( 'the docs-site mirror of the project status', () => {
	it( 'is regenerated from PROJECT-STATUS.md rather than maintained by hand', () => {
		// The same contract `tests/token-inventory.test.js` holds the token inventory to: a generated
		// artifact is committed so the site builds and the diff is reviewable, and a test regenerates
		// it to prove nobody edited the copy instead of the source. Two hand-kept copies of a status
		// page is how one of them ends up describing a release the other does not.
		const {
			renderProjectStatusPage,
		} = require( '../scripts/sync-project-status.mjs' );

		const generated = renderProjectStatusPage( repositoryRoot );
		const committed = fs.readFileSync(
			path.join(
				repositoryRoot,
				'docs-app/src/content/docs/project-status.md'
			),
			'utf8'
		);

		expect( committed ).toBe( generated );
	} );
} );
