import { chromium } from 'playwright';
const OUT='C:/Users/pc/AppData/Local/Temp/claude/C--wamp64-www-perego/78f68e1f-dee9-4924-8a5e-3d0472708309/scratchpad/shots';
const b = await chromium.launch({ args:['--host-resolver-rules=MAP perego.local 127.0.0.1'] });
const p = await (await b.newContext({ viewport:{width:1280,height:900} })).newPage();
await p.goto('http://perego.local/?nocache='+Date.now(), {waitUntil:'commit'});
await p.waitForTimeout(120);
await p.screenshot({ path:`${OUT}/preloader3.png` });
const r = await p.evaluate(()=>{ const el=document.querySelector('.preloader'); const b=el.getBoundingClientRect(); return {top:Math.round(b.top),h:Math.round(b.height),vh:innerHeight,hidden:el.classList.contains('is-hidden')}; });
console.log(JSON.stringify(r));
await b.close();
